export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
export const DECREMENTBYUSERINPUT = 'DECREMENTBYUSERINPUT';
export const INCREMENTTONEXTODDNUMBER = 'INCREMENTTONEXTODDNUMBER';
export const INCREMENTBYRANDOMNO = 'INCREMENTBYRANDOMNO';
export const MOVE_TO_NEXT_ODD_NO = 'MOVE_TO_NEXT_ODD_NO';

